export const CAR_BRANDS = [
  { key: 'abarth', label: 'Abarth', icon: '/logos/abarth.png' },
  { key: 'alfa', label: 'Alfa', icon: '/logos/alfa.png' },
  { key: 'audi', label: 'Audi', icon: '/logos/audi.png' },
  { key: 'ascari', label: 'Ascari', icon: '/logos/logocut.png' },
  { key: 'aston', label: 'Aston', icon: '/logos/aston.png' },
  { key: 'bentley', label: 'Bentley', icon: '/logos/bentley.png' },
  { key: 'bmw', label: 'BMW', icon: '/logos/bmw.png' },
  { key: 'bugatti', label: 'Bugatti', icon: '/logos/bugatti.png' },
  { key: 'cadillac', label: 'Cadillac', icon: '/logos/cadillac.png' },
  { key: 'chevrolet', label: 'Chevrolet', icon: '/logos/chevrolet.png' },
  { key: 'citroën', label: 'Citroën', icon: '/logos/citroën.png' },
  { key: 'dacia', label: 'Dacia', icon: '/logos/dacia.png' },
  { key: 'dodge', label: 'Dodge', icon: '/logos/dodge.png' },
  { key: 'ferrari', label: 'Ferrari', icon: '/logos/ferrari.png' },
  { key: 'fiat', label: 'FIAT', icon: '/logos/fiat.png' },
  { key: 'ford', label: 'Ford', icon: '/logos/ford.png' },
  { key: 'honda', label: 'Honda', icon: '/logos/honda.png' },
  { key: 'hyundai', label: 'Hyundai', icon: '/logos/hyundai.png' },
  { key: 'jaguar', label: 'Jaguar', icon: '/logos/jaguar.png' },
  { key: 'jeep', label: 'Jeep', icon: '/logos/jeep.png' },
  { key: 'kia', label: 'Kia', icon: '/logos/kia.png' },
  { key: 'lamborghini', label: 'Lamborghini', icon: '/logos/lambo.png' },
  { key: 'landrover', label: 'LandRover', icon: '/logos/landrover.png' },
  { key: 'lexus', label: 'Lexus', icon: '/logos/lexus.png' },
  { key: 'maserati', label: 'Maserati', icon: '/logos/maserati.png' },
  { key: 'mazda', label: 'Mazda', icon: '/logos/mazda.png' },
  { key: 'mercedes', label: 'Mercedes', icon: '/logos/benz.png' },
  { key: 'nissan', label: 'Nissan', icon: '/logos/nissan.png' },
  { key: 'peugeot', label: 'Peugeot', icon: '/logos/peugeot.png' },
  { key: 'porsche', label: 'Porsche', icon: '/logos/porsche.png' },
  { key: 'renault', label: 'Renault', icon: '/logos/renault.png' },
  { key: 'seat', label: 'Seat', icon: '/logos/seat.png' },
  { key: 'skoda', label: 'Skoda', icon: '/logos/skoda.png' },
  { key: 'subaru', label: 'Subaru', icon: '/logos/subaru.png' },
  { key: 'suzuki', label: 'Suzuki', icon: '/logos/suzuki.png' },
  { key: 'tesla', label: 'Tesla', icon: '/logos/tesla.png' },
  { key: 'toyota', label: 'Toyota', icon: '/logos/toyota.png' },
  { key: 'volkswagen', label: 'Volkswagen', icon: '/logos/volkswagen.png' },
  { key: 'volvo', label: 'Volvo', icon: '/logos/volvo.png' },
];

export const FUEL_TYPES = [
  { key: 'benzina', label: 'Benzina', icon: '/fuel/benzina.jpeg' },
  { key: 'diesel', label: 'Diesel', icon: '/fuel/diesel.jpeg' },
  { key: 'elettrico', label: 'Elettrico', icon: '/fuel/elettrico.jpeg' },
  { key: 'gpl', label: 'Metano / GPL', icon: '/fuel/gpl.jpeg' },
  { key: 'idrogeno', label: 'Idrogeno', icon: '/fuel/idro.jpeg' },
];

// ✅ MODELLI per marca (chiave = key della marca)
export const CAR_MODELS_BY_BRAND_KEY: Record<string, string[]> = {
  abarth: ['500', '595', '695', 'Grande punto', '124 spider'],
  alfa: ['MiTo', 'Giulietta', 'Giulia', 'Stelvio', 'Tonale', '4C', '8C Competizione', 'Brera', 'Spider', '159', '147', 'GT'],
  audi: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q1', 'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q6', 'Q7', 'Q8', 'TT', 'TTS', 'R8', 'e-tron GT', 'RS3', 'RS4', 'RS6', 'RS Q8'],
  ascari: ['3000', 'A10'],
  aston: ['Vantage', 'DB11', 'DB12', 'DBS', 'DBX', 'Valkyrle'],
  bentley: ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  bmw: ['Serie 1', 'Serie 2', 'Serie 3', 'Serie 4', 'Serie 5', 'Serie 6', 'Serie 7', 'Serie 8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'i5', 'i7', 'ix', 'M2', 'M3', 'M4', 'M5', 'XM'],
  bugatti: ['Chiron', 'Veyron', 'Divo', 'Bolide'],
  cadillac: ['CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6', 'Lyriq'],
  chevrolet: ['Spark', 'Aveo', 'Malibu', 'Camaro', 'Corvette', 'Silverado', 'Tahoe', 'Suburban'],
  citroën: ['C1', 'C2', 'C3', 'C4', 'C5', 'Berlingo', 'DS3'],
  dacia: ['Sandero', 'Logan', 'Duster', 'Jogger', 'Spring'],
  dodge: ['Charger', 'Challenger', 'Durango', 'Hornet'],
  ferrari: ['Roma', 'Portofino','F8 Tributo', '296 GTB', 'SF90', 'Purosangue', '812 Superfast', 'LaFerrari', 'Enzo', '458', '488'],
  fiat: ['Panda', '500', 'Punto', '600', 'Bravo', '124 Spider', 'Doblo', 'Fiorino'],
  ford: ['Fiesta', 'Focus', 'Mondeo', 'Puma', 'Kuga', 'Explorer', 'Mustang', 'Ranger', 'F-150'],
  honda: ['Civic', 'Accord', 'Jazz', 'HR-V', 'CR-V', 'NSX', 'e'],
  hyundai: ['i10', 'i20', 'i30', 'Kona', 'Tucson', 'Santa Fe', 'IONIQ 5', 'IONIQ 6', 'Bayon'],
  jaguar: ['XE', 'XF', 'F-PACE', 'E-PACE', 'I-PACE', 'F-Type'],
  jeep: ['Renegade', 'Compass', 'Wrangler', 'Grand Cherokee', 'Avenger'],
  kia: ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento', 'EV6', 'EV9'],
  lamborghini: ['Huracàn', 'Aventador', 'Revuelto', 'Urus', 'Gallardo'],
  landrover: ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque'],
  lexus: ['IS', 'ES', 'LS', 'RX', 'NX', 'UX','LC'],
  maserati: ['Ghibli', 'Quattroporte', 'Levante', 'Grecale', 'MC20', 'GrandTurismo'],
  mazda: ['Madza2', 'Madza3', 'Madza6', 'CX-3', 'CX-5', 'CX-60','MX-5'],
  mercedes: ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Classe G', 'EQS','EQE', 'EQA','AMG GT'],
  nissan: ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Leaf', 'GT-R'],
  peugeot: ['108', '208', '308', '508', '2008', '3008', '5008', 'Partner', 'Traveller'],
  porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', '718 Boxster', '718 Cayman'],
  renault: ['Clio', 'Megane', 'Captur', 'Austral', 'Scenic', 'Twingo', 'Kangoo'],
  seat: ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
  skoda: ['Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq'],
  subaru: ['Impreza', 'WRX', 'Forester', 'Outback', 'Xv', 'Crosstrek'],
  suzuki: ['Swift', 'Ignis', 'Vitara', 'S-Cross', 'Jimny'],
  tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck'],
  toyota: ['Aygo', 'Yaris', 'Corolla', 'Camry', 'RAV4', 'C-HR', 'Prius', 'Land Cruiser', 'Hilux', 'Supra'],
  volkswagen: ['Polo', 'Golf', 'Lupo', 'Fox', 'Passat', 'Arteon', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'ID.3', 'ID.4', 'ID.Buzz'],
  volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'EX30', 'EX90'],
};